
CREATE DATABASE IF NOT EXISTS usjr2;

USE usjr2;


CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
SELECT * FROM users;

DESCRIBE users;
